<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<ol class="items">
    <li>
        <select class="am_shopby_filter_<?php echo $filterSetting->getFilterCode(); ?>">
            <option value="<?php echo $block->escapeUrl($this->getClearUrl()) ?>">&nbsp;</option>
            <?php foreach ($filterItems as $filterItem):
                $disabled = ($filterItem->getCount() == 0) ? ' disabled' : "";
                $selected = ($this->checkedFilter($filterItem)) ? ' selected' : "";
                $url = $block->escapeUrl($filterItem->getUrl());
                $label = $filterItem->getLabel();
                if ($filterSetting->isShowProductQuantities()) {
                    $label .= ' <span class="count">(' . $filterItem->getCount() . ')</span>';
                }
                ?>
                <option value="<?php echo $url ?>" <?php echo $disabled . $selected ?>><?php echo $label ?></option>
            <?php endforeach ?>
            <script type="text/x-magento-init">
            {
                ".am_shopby_filter_<?php echo $filterSetting->getFilterCode(); ?>": {
                    "amShopbyFilterDropdown": {"currentValue":<?php echo 1 ?>}
                }
            }
            </script>
        </select>
    </li>
</ol>

<?php if($filterSetting->isShowTooltip()): ?>
    <?php
    $tooltipTemplate = '<span class="tooltip amshopby-filter-tooltip" style="float:right" title="{content}"><img src="'.$tooltipUrl.'"</img></span>';
    ?>
    <script type="text/x-magento-init">
            {
                ".am_shopby_filter_items_<?=$filterSetting->getFilterCode()?>": {
                    "amShopbyFilterAddTooltip": {
                        "content": <?=json_encode($filterSetting->getTooltip())?>,
                        "tooltipTemplate": <?=json_encode($tooltipTemplate)?>
                    }
                }
            }
    </script>
<?php endif; ?>
