<?php
	$_themeHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');
	$_mobileHelper = $this->helper('Codazon\ThemeOptions\Helper\Mobile');
	$_fontList = $_themeHelper->getConfig('variables/font/f_google_font');
	$_fontWeights = ':200,200italic,300,300italic,400,400italic,500,500italic,600italic,600italic,700,700italic,800,800italic,900,900italic';
	
?>
<?php if ($_fontList): ?>
<?php 
	if(is_array($_fontList)){
		$fontArr = $_fontList;
	}
	else{
		$fontArr = explode(',',$_fontList);		
	}
	
	// font weight
	$fontWeightOption = str_replace(' ','', $_themeHelper->getConfig('variables/font/f_google_font_weight'));
	if ($fontWeightOption)
		$_fontWeights = ':'.$fontWeightOption;	
		
    if($block->getRequest()->isSecure())
        $google_font_link = "https";
    else
        $google_font_link = "http";
    $google_font_link.= "://fonts.googleapis.com/css";    
   
?>
<?php endif ?>
<?php if($fontArr):?>

<?php
   	foreach($fontArr as $font){
   		$font = trim($font);
  		echo  "<link href='".$google_font_link."?family=".str_replace(' ','+',$font)."$_fontWeights&amp;subset=latin,cyrillic-ext,cyrillic,greek-ext,greek,vietnamese,latin-ext' rel='stylesheet' type='text/css' />";
      }
?>
<?php endif; ?>
<script type="text/javascript">
	var ThemeOptions = {
		box_wide: <?php echo $_themeHelper->getConfig('general_section/layout/box_wide') ?>,
		rtl_layout: <?php echo $_themeHelper->getConfig('general_section/layout/enable_rtl') ?>,
		sticky_header: <?php echo $_themeHelper->getConfig('general_section/header/sticky_header') ?>		
	};
	require(['jquery'],function($){
		if(ThemeOptions.box_wide)
		{
            $('body').addClass('box-layout');
        }
        if(ThemeOptions.rtl_layout)
        {
        	$('body').addClass('rtl-layout');
        }
        <?php if($_mobileHelper->is('iOS')): ?>
        	$('body').addClass('iMenu');
        <?php endif; ?>
    });        	
</script>
