<?php
// Get videoID attribute
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $this->getProduct();
$youtubevideoid = $_product->getAdditionalVideo();
// Check to see if the product has a video ID
if ($youtubevideoid != ""){
// If it does, show the video
?>
<?php echo $youtubevideoid ?>
<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/<?php /*echo $youtubevideoid;*/ ?>" frameborder="0" allowfullscreen></iframe> -->
<?php
} ?>
