<?php
	$themes = $block->getThemes();
	$items = [];
	$activeTheme = '';
	foreach($themes as $theme){
		if($theme->getThemeId() == $block->getCurrentThemeId()){
			$activeTheme = $theme;
		}else{
			$items[] = $theme;
		}
	}
?>
<ul class="themes-grid">
	<?php if($activeTheme): ?>
	<li class="theme-item active">
		<a class="theme-image" href="<?php echo $block->getCustomThemeUrl($activeTheme->getThemeId()); ?>">
            <span class="image-wrap move-long" style="background-image: url('<?php echo $block->getThemeReviewImageUrl($activeTheme); ?>');"></span>
        </a>
        <div class="control">
        	<span class="theme-name"><strong><?php echo __('Activated') ?>:</strong> <?php echo $activeTheme->getThemeTitle() ?></span>
        	<a class="btn-customize" href="#customize_form"><span><span><?php echo __('Customize') ?></span></span></a>
        </div>
	</li>
	<?php endif ?>
</ul>
<div id="customize_form" class="customize-form">
	<div class="setting-icon"></div>
	<div class="theme-title">
		<label><?php echo __('Current theme setting') ?>:</label><label><?php echo $activeTheme->getThemeTitle() ?></label>
	</div>
</div>
